Feature/develop boilers
DavidArroyo92/CaldAr pull request #10
Opened 2020-11-30 13:17 UTC by maxivgg

2020-12-01 13:50 UTC, DavidArroyo92 approved these changes

2020-12-01 20:47 UTC, Bollero-RR requested changes

2020-12-01 20:47 UTC, Bollero-RR commented on controllers/boilers.js
> +  if(!req.body.id || !req.body.typeId || !req.body.maintainceRate || !req.body.hourMaintainceCost || !req.body.hourEventualCost){
esta validacion deberia ir abajo del --> "exports.update = (req, res) => { "

2020-12-01 20:47 UTC, Bollero-RR commented on controllers/boilers.js
> +  const id = req.body.id
estas constantes estan de mas si ya les estas pasando req.body al findOneAndUpdate. podes elegir si dejar las constantes y hacer:

Boiler.findOneAndUpdate({id}, {
id,
typeId,
maintainceRate,
hourMaintainceCost,
hourEventualCost
}, {useFindAndModify: false})

o si preferis borrar esas constantes...
el findOneAndUpdate te quedaria asi:
Boiler.findOneAndUpdate({id: req.body.id}, req.body, {useFindAndModify: false})

2020-12-01 20:47 UTC, Bollero-RR commented on controllers/boilers.js
> +//Get single Boiler email
probablemente el nombre del comentario este mal... ya que no creo estemos trayendo Boiler por email

2020-12-01 20:47 UTC, Bollero-RR commented on controllers/boilers.js
> +  if(!req.body.id || !req.body.typeId || !req.body.maintainceRate || !req.body.hourMaintainceCost || !req.body.hourEventualCost){
este if iria despues de --> "exports.create = (req, res) => {"

2020-12-01 21:25 UTC, Bollero-RR approved these changes

2020-12-08 14:21 UTC, Bollero-RR requested changes
ver mensaje de slack correspondiente a las validaciones de los id

2020-12-08 14:21 UTC, Bollero-RR commented on models/boiler.js
> +        id: Number,
eliminar este campo

2020-12-08 14:21 UTC, Bollero-RR commented on models/boiler.js
> +        typeId: Number,
actualizar por
typeId:{
type: mongoose.Schema.Types.ObjectId
}

2020-12-08 20:38 UTC, Bollero-RR requested changes

2020-12-08 20:38 UTC, Bollero-RR commented on controllers/boilers.js
>    const newBoiler = new Boiler({
misma actualizacion que para el create de customers

2020-12-08 20:38 UTC, Bollero-RR commented on controllers/boilers.js
> +  Boiler.findOne({ _id: req.body.id })
esta validacion esta de más, misma razon que la de customers

2020-12-08 20:38 UTC, Bollero-RR commented on controllers/boilers.js
> +  Boiler.findOneAndUpdate({ _id: req.body.id }, req.body, { useFindAndModify: false })
el id lo sacamos del req.params.id

2020-12-08 20:38 UTC, Bollero-RR commented on controllers/boilers.js
>      });
sacar el !req.body.id de la validacion de arriba porque, el id lo sacamos del req.params.id

2020-12-09 15:03 UTC, Bollero-RR requested changes

2020-12-09 15:03 UTC, Bollero-RR commented on controllers/boilers.js
> +          message: `Boiler with id ${req.params.id} was not exist`,
cambiar por --> message: `Boiler with id ${req.params.id} does not exist`,

2020-12-09 15:03 UTC, Bollero-RR commented on controllers/boilers.js
> +          message: `Boiler with Type id ${req.params.type} was not exist`,
cambiar por. --> message: `Boiler with Type id ${req.params.type} does not exist`,

2020-12-09 21:26 UTC, Bollero-RR approved these changes

2020-12-09 23:26 UTC, merged