Feature/develop building
DavidArroyo92/CaldAr pull request #12
Opened 2020-12-01 13:28 UTC by DavidArroyo92

2020-12-01 15:08 UTC, maxivgg reviewed
todo okey

2020-12-01 21:02 UTC, Bollero-RR requested changes

2020-12-01 21:02 UTC, Bollero-RR commented on controllers/buildings.js
> +  if (!req.body.id || !req.body.businessName || !req.body.email || !req.body.adress || !req.body.phone  || !req.body.boilersAmount || !req.body.boilersType){
este if deberia ir despues del --> exports.create = (req, res) => {
para no asignar las constantes en vano

2020-12-01 21:02 UTC, Bollero-RR commented on controllers/buildings.js
> +    const building = new Building({
cambiar por  --> const newBuilding = new Building({

2020-12-01 21:02 UTC, Bollero-RR commented on controllers/buildings.js
> +  building
cambiar por newBuilding

2020-12-01 21:02 UTC, Bollero-RR commented on controllers/buildings.js
> +    .save(building)
cambiar por newBuilding -->  .save(newBuilding)

2020-12-01 21:34 UTC, Bollero-RR requested changes

2020-12-01 21:34 UTC, Bollero-RR commented on models/buildings.js
> +                email: String,
agregar --> boilersId: Array

2020-12-01 21:34 UTC, Bollero-RR commented on models/buildings.js
> +                email: String,
agregar respectivamente donde corresponde el campo faltante (create, modify, etc)

2020-12-08 14:15 UTC, Bollero-RR requested changes
revisar el comentario respecto de las validaciones de ids

2020-12-08 14:15 UTC, Bollero-RR commented on models/buildings.js
> +                boilersType: String,
este type deberia ser un Array de Strings.
boilersType: [{
type: String
}],

2020-12-08 14:15 UTC, Bollero-RR commented on models/buildings.js
> +                boilersId: Array
actualizar a:
boilersId: [{
type: mongoose.Schema.Types.ObjectId
}],

2020-12-08 14:16 UTC, Bollero-RR commented on models/buildings.js
> +                id: Number,
eliminar este campo

2020-12-08 20:00 UTC, Bollero-RR requested changes

2020-12-08 20:00 UTC, Bollero-RR commented on controllers/buildings.js
> -    boilersId: boilersId
no tenes que borrar el boilersId del create, porque como lo guardarias sino.
de paso acordate que hacer  por ejemplo { email } es lo mismo que {email : email }
asi que podes dejarlo como
 const newBuilding = new Building({
    businessName,
    email,
    adress,
    phone,
    boilersId
  })

2020-12-08 20:00 UTC, Bollero-RR commented on controllers/buildings.js
> +  !req.body.email ||
la validacion de boilersId no esta de más, porque tenes que validar que exista en el req.body

2020-12-08 20:00 UTC, Bollero-RR commented on controllers/buildings.js
>    Building.findOne({_id: req.params.id})
este findOne esta de más fijate que estas haciendo dos veces consulta al server para saber si existe. Cuando el hecho de saber si existe o no, directamente lo sacas con la consulta de abajo que es la de findOneAndUpdate, que te deberia devolver o null o por el catch que no se encontro nada.

2020-12-08 20:50 UTC, Bollero-RR approved these changes

2020-12-10 00:08 UTC, merged